<?php
session_start();
include('db.php');
if($_SESSION['username'])
{
	$id=$_SESSION['uid'];
  ?>

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>


table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #D6EEEE;
}
body {
  margin: 0;
  font-size: 28px;
  font-family: Arial, Helvetica, sans-serif;
}

.header {
  background-color: #f1f1f1;
  padding: 5px;
  text-align: left;
}


.content {
  padding: 16px;
}

.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

.sticky + .content {
  padding-top: 60px;
}


td:hover {background-color: coral;}
  
.open {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
  }
a{
  text-decoration: none;
}

</style>


</head>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<body>

<?php include 'usernavbar.html'
?>   

<button style='font-size:24px;  position: absolute; top: 10px; right: 10px;'>
<?php echo $_SESSION['username'];?> <i class='fas fa-user-alt'></i></button>

<div class="header" >
  <h2>BIDEAL</h2>
</div>

<div class="content">

<form method="POST">
    <table>
      <tr>
      <th>Product</th>
      <th>Your Bid Amount</th>
      <th>Original prize</th> 
      <th>Date</th> 
      <th>Payment</th>
      </tr>
      <?php
      $sq=mysqli_query($con,"select * from products where userbid_id='$id' and uid!=userbid_id");
      while($r=mysqli_fetch_assoc($sq))
      {
      ?>
      
        <tr>
      <td><input type="text" hidden name="cartid" id="cartid" value="<?php echo $r['id'] ?>" ></td>
      <td><input type="text" hidden name="amount" id="amount" value="<?php echo $r['start_bid']  ?>" ></td>
      <tr>
      <td><?php echo $r['name']  ?></td>
      <td><?php echo $r['start_bid']  ?></td>
      <td><?php echo $r['regular_price']  ?></td>
      <td><?php echo date('d-m-Y',strtotime($r['end_date'] )) ?></td>
      <td><?php echo $r['pay_status']  ?></td>
      <?php
      $s=$r['pay_status'];
      if($s=="not paid")
      {
      ?>
      <td><button name="button12" >Make Payment</button></td>
      <?php
      }
      ?>
      </tr>
      
      <?php
      }
      ?>
    
    </table>
</form>



</div>
<?php
if(isset($_POST['button12']))
{
  
  $id=$_POST['cartid'];
  $amount=$_POST['amount'];
  ?>
              
  <form action="paysu.php?id=<?php echo $id; ?> && amo=<?php echo $amount ?>" method="POST">            
<script

    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_RoLijFIA4QltjT" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Alpha Care Home"
    data-description=""
    data-image=""
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden" >
</form>
</script>

<?php
}
?>

</body>
</html>




<?php
} 

else
{
  header("Location: http://localhost/bidtemplate/login.php");
}
  ?>


